### ISSUE TITLE
alert dialog issue.How to fix it?

### ISSUE THREAD

**Issue by shintumintu** [FilledStacks/flutter-tutorials#81]
E/flutter (25347): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'call' was called on null.
E/flutter (25347): Receiver: null
E/flutter (25347): Tried calling: call()
E/flutter (25347): #0      DialogService.showDialog 
package:glowchat/services/dialog_service.dart:26
E/flutter (25347): #1      LoginViewModel.login 
package:glowchat/viewmodels/login_view_model.dart:39
E/flutter (25347): <asynchronous suspension>
E/flutter (25347): #2      LoginScreen.build.<anonymous closure>.<anonymous closure> 
package:glowchat/…/login/login_screen.dart:126
E/flutter (25347): #3      GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:182
E/flutter (25347): #4      TapGestureRecognizer.handleTapUp 
package:flutter/…/gestures/tap.dart:504
E/flutter (25347): #5      BaseTapGestureRecognizer._checkUp 
package:flutter/…/gestures/tap.dart:282
E/flutter (25347): #6      BaseTapGestureRecognizer.acceptGesture 
package:flutter/…/gestures/tap.dart:254
E/flutter (25347): #7      GestureArenaManager.sweep 
package:flutter/…/gestures/arena.dart:156
E/flutter (25347): #8      GestureBinding.handleEvent 
package:flutter/…/gestures/binding.dart:222
E/flutter (25347): #9      GestureBinding.dispatchEvent 
package:flutter/…/gestures/binding.dart:198
E/flutter (25347): #10     GestureBinding._handlePointerEvent 
package:flutter/…/gestures/binding.dart:156
E/flutter (25347): #11     GestureBinding._flushPointerEventQueue 
package:flutter/…/gestures/binding.dart:102
E/flutter (25347): #12     GestureBinding._handlePointerDataPacket 
package:flutter/…/gestures/binding.dart:86
E/flutter (25347): #13     _rootRunUnary  (dart:async/zone.dart:1196:13)
E/flutter (25347): #14     _CustomZone.runUnary  (dart:async/zone.dart:1085:19)
E/flutter (25347): #15     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:987:7)
E/flutter (25347): #16     _invoke1  (dart:ui/hooks.dart:275:10)
E/flutter (25347): #17     _dispatchPointerDataPacket  (dart:ui/hooks.dart:184:5)
E/flutter (25347):

**Comment by FilledStacks** [comment]
I have no idea what's causing that. Things work fine on my side. What version is your stacked_services on, what version is your get on?
